# Generated by Django 5.0.6 on 2024-05-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='title',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
