# Generated by Django 5.0.6 on 2024-05-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_delete_annonce_band_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='band',
            name='title',
        ),
    ]
